<?php

namespace App\Repository;

use App\Entity\Coaster;

/**
 * SeatingTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SeatingTypeRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @param Coaster $coaster
     * @return mixed|string
     */
    public function getHeatMapInfo(Coaster $coaster)
    {
        try {
            return $this->getEntityManager()
                ->createQueryBuilder()
                ->select('s.lines as rows')
                ->addSelect('s.columns as columns')
                ->from('App:SeatingType', 's')
                ->where('s.id = :coasterType')
                ->setParameter('coasterType', $coaster->getSeatingType())
                ->getQuery()
                ->getSingleResult();
        } catch (\Exception $e) {
            return ['nb' => 0, 'name' => 'Unknown'];
        }
    }
}
